---

- name: 'Check mandatory variables are defined'
  assert:
    that:
      - loki_url is defined
      - postgres_username is defined
      - postgres_password is defined

- name: Create the postgres data volumne
  docker_volume:
    name: postgres-data

- name: Create database container
  docker_container:
    name: "postgres-database"
    image: "{{ application_name }}:latest"
    restart_policy: "always"
    cleanup: true
    exposed_ports:
      - "5432"
    published_ports: "{{ ['0.0.0.0:5432:5432'] if should_publish_ports else [] }}"
    networks:
      - name: "{{ network_name }}"
    log_driver: "loki"
    log_options:
      loki-url: "{{ loki_url }}"
      loki-batch-size: "400"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env:
      POSTGRES_USER: "{{ postgres_username }}"
      POSTGRES_PASSWORD: "{{ postgres_password }}"

- name: Setup restic backups
  include_role:
    name: ansible-backups
    tasks_from: setup-restic-backups
  vars:
    file_path: "/var/lib/docker/volumes/postgres-data"
